package com.ashu.as_codepicker;

import java.util.ArrayList;
import java.util.List;

public class Utils {

    public static final int INTENT_FOR_CODE = 802;
    public static final String KEY_FOR_NAME = "name", KEY_FOR_CODE = "code",KEY_FOR_CODE_WITH_PLUS="withPlus";
    public static List<ModelCountyCode> getLibraryMasterCountriesEnglish() {
        List<ModelCountyCode> countries = new ArrayList<>();
        countries.add(new ModelCountyCode("ad", "376", "Andorra"));
        countries.add(new ModelCountyCode("ae", "971", "United Arab Emirates (UAE)"));
        countries.add(new ModelCountyCode("af", "93", "Afghanistan"));
        countries.add(new ModelCountyCode("ag", "1", "Antigua and Barbuda"));
        countries.add(new ModelCountyCode("ai", "1", "Anguilla"));
        countries.add(new ModelCountyCode("al", "355", "Albania"));
        countries.add(new ModelCountyCode("am", "374", "Armenia"));
        countries.add(new ModelCountyCode("ao", "244", "Angola"));
        countries.add(new ModelCountyCode("aq", "672", "Antarctica"));
        countries.add(new ModelCountyCode("ar", "54", "Argentina"));
        countries.add(new ModelCountyCode("as", "1", "American Samoa"));
        countries.add(new ModelCountyCode("at", "43", "Austria"));
        countries.add(new ModelCountyCode("au", "61", "Australia"));
        countries.add(new ModelCountyCode("aw", "297", "Aruba"));
        countries.add(new ModelCountyCode("ax", "358", "Åland Islands"));
        countries.add(new ModelCountyCode("az", "994", "Azerbaijan"));
        countries.add(new ModelCountyCode("ba", "387", "Bosnia And Herzegovina"));
        countries.add(new ModelCountyCode("bb", "1", "Barbados"));
        countries.add(new ModelCountyCode("bd", "880", "Bangladesh"));
        countries.add(new ModelCountyCode("be", "32", "Belgium"));
        countries.add(new ModelCountyCode("bf", "226", "Burkina Faso"));
        countries.add(new ModelCountyCode("bg", "359", "Bulgaria"));
        countries.add(new ModelCountyCode("bh", "973", "Bahrain"));
        countries.add(new ModelCountyCode("bi", "257", "Burundi"));
        countries.add(new ModelCountyCode("bj", "229", "Benin"));
        countries.add(new ModelCountyCode("bl", "590", "Saint Barthélemy"));
        countries.add(new ModelCountyCode("bm", "1", "Bermuda"));
        countries.add(new ModelCountyCode("bn", "673", "Brunei Darussalam"));
        countries.add(new ModelCountyCode("bo", "591", "Bolivia, Plurinational State Of"));
        countries.add(new ModelCountyCode("br", "55", "Brazil"));
        countries.add(new ModelCountyCode("bs", "1", "Bahamas"));
        countries.add(new ModelCountyCode("bt", "975", "Bhutan"));
        countries.add(new ModelCountyCode("bw", "267", "Botswana"));
        countries.add(new ModelCountyCode("by", "375", "Belarus"));
        countries.add(new ModelCountyCode("bz", "501", "Belize"));
        countries.add(new ModelCountyCode("ca", "1", "Canada"));
        countries.add(new ModelCountyCode("cc", "61", "Cocos (keeling) Islands"));
        countries.add(new ModelCountyCode("cd", "243", "Congo, The Democratic Republic Of The"));
        countries.add(new ModelCountyCode("cf", "236", "Central African Republic"));
        countries.add(new ModelCountyCode("cg", "242", "Congo"));
        countries.add(new ModelCountyCode("ch", "41", "Switzerland"));
        countries.add(new ModelCountyCode("ci", "225", "Côte D'ivoire"));
        countries.add(new ModelCountyCode("ck", "682", "Cook Islands"));
        countries.add(new ModelCountyCode("cl", "56", "Chile"));
        countries.add(new ModelCountyCode("cm", "237", "Cameroon"));
        countries.add(new ModelCountyCode("cn", "86", "China"));
        countries.add(new ModelCountyCode("co", "57", "Colombia"));
        countries.add(new ModelCountyCode("cr", "506", "Costa Rica"));
        countries.add(new ModelCountyCode("cu", "53", "Cuba"));
        countries.add(new ModelCountyCode("cv", "238", "Cape Verde"));
        countries.add(new ModelCountyCode("cw", "599", "Curaçao"));
        countries.add(new ModelCountyCode("cx", "61", "Christmas Island"));
        countries.add(new ModelCountyCode("cy", "357", "Cyprus"));
        countries.add(new ModelCountyCode("cz", "420", "Czech Republic"));
        countries.add(new ModelCountyCode("de", "49", "Germany"));
        countries.add(new ModelCountyCode("dj", "253", "Djibouti"));
        countries.add(new ModelCountyCode("dk", "45", "Denmark"));
        countries.add(new ModelCountyCode("dm", "1", "Dominica"));
        countries.add(new ModelCountyCode("do", "1", "Dominican Republic"));
        countries.add(new ModelCountyCode("dz", "213", "Algeria"));
        countries.add(new ModelCountyCode("ec", "593", "Ecuador"));
        countries.add(new ModelCountyCode("ee", "372", "Estonia"));
        countries.add(new ModelCountyCode("eg", "20", "Egypt"));
        countries.add(new ModelCountyCode("er", "291", "Eritrea"));
        countries.add(new ModelCountyCode("es", "34", "Spain"));
        countries.add(new ModelCountyCode("et", "251", "Ethiopia"));
        countries.add(new ModelCountyCode("fi", "358", "Finland"));
        countries.add(new ModelCountyCode("fj", "679", "Fiji"));
        countries.add(new ModelCountyCode("fk", "500", "Falkland Islands (malvinas)"));
        countries.add(new ModelCountyCode("fm", "691", "Micronesia, Federated States Of"));
        countries.add(new ModelCountyCode("fo", "298", "Faroe Islands"));
        countries.add(new ModelCountyCode("fr", "33", "France"));
        countries.add(new ModelCountyCode("ga", "241", "Gabon"));
        countries.add(new ModelCountyCode("gb", "44", "United Kingdom"));
        countries.add(new ModelCountyCode("gd", "1", "Grenada"));
        countries.add(new ModelCountyCode("ge", "995", "Georgia"));
        countries.add(new ModelCountyCode("gf", "594", "French Guyana"));
        countries.add(new ModelCountyCode("gh", "233", "Ghana"));
        countries.add(new ModelCountyCode("gi", "350", "Gibraltar"));
        countries.add(new ModelCountyCode("gl", "299", "Greenland"));
        countries.add(new ModelCountyCode("gm", "220", "Gambia"));
        countries.add(new ModelCountyCode("gn", "224", "Guinea"));
        countries.add(new ModelCountyCode("gp", "450", "Guadeloupe"));
        countries.add(new ModelCountyCode("gq", "240", "Equatorial Guinea"));
        countries.add(new ModelCountyCode("gr", "30", "Greece"));
        countries.add(new ModelCountyCode("gt", "502", "Guatemala"));
        countries.add(new ModelCountyCode("gu", "1", "Guam"));
        countries.add(new ModelCountyCode("gw", "245", "Guinea-bissau"));
        countries.add(new ModelCountyCode("gy", "592", "Guyana"));
        countries.add(new ModelCountyCode("hk", "852", "Hong Kong"));
        countries.add(new ModelCountyCode("hn", "504", "Honduras"));
        countries.add(new ModelCountyCode("hr", "385", "Croatia"));
        countries.add(new ModelCountyCode("ht", "509", "Haiti"));
        countries.add(new ModelCountyCode("hu", "36", "Hungary"));
        countries.add(new ModelCountyCode("id", "62", "Indonesia"));
        countries.add(new ModelCountyCode("ie", "353", "Ireland"));
        countries.add(new ModelCountyCode("il", "972", "Israel"));
        countries.add(new ModelCountyCode("im", "44", "Isle Of Man"));
        countries.add(new ModelCountyCode("is", "354", "Iceland"));
        countries.add(new ModelCountyCode("in", "91", "India"));
        countries.add(new ModelCountyCode("io", "246", "British Indian Ocean Territory"));
        countries.add(new ModelCountyCode("iq", "964", "Iraq"));
        countries.add(new ModelCountyCode("ir", "98", "Iran, Islamic Republic Of"));
        countries.add(new ModelCountyCode("it", "39", "Italy"));
        countries.add(new ModelCountyCode("je", "44", "Jersey "));
        countries.add(new ModelCountyCode("jm", "1", "Jamaica"));
        countries.add(new ModelCountyCode("jo", "962", "Jordan"));
        countries.add(new ModelCountyCode("jp", "81", "Japan"));
        countries.add(new ModelCountyCode("ke", "254", "Kenya"));
        countries.add(new ModelCountyCode("kg", "996", "Kyrgyzstan"));
        countries.add(new ModelCountyCode("kh", "855", "Cambodia"));
        countries.add(new ModelCountyCode("ki", "686", "Kiribati"));
        countries.add(new ModelCountyCode("km", "269", "Comoros"));
        countries.add(new ModelCountyCode("kn", "1", "Saint Kitts and Nevis"));
        countries.add(new ModelCountyCode("kp", "850", "North Korea"));
        countries.add(new ModelCountyCode("kr", "82", "South Korea"));
        countries.add(new ModelCountyCode("kw", "965", "Kuwait"));
        countries.add(new ModelCountyCode("ky", "1", "Cayman Islands"));
        countries.add(new ModelCountyCode("kz", "7", "Kazakhstan"));
        countries.add(new ModelCountyCode("la", "856", "Lao People's Democratic Republic"));
        countries.add(new ModelCountyCode("lb", "961", "Lebanon"));
        countries.add(new ModelCountyCode("lc", "1", "Saint Lucia"));
        countries.add(new ModelCountyCode("li", "423", "Liechtenstein"));
        countries.add(new ModelCountyCode("lk", "94", "Sri Lanka"));
        countries.add(new ModelCountyCode("lr", "231", "Liberia"));
        countries.add(new ModelCountyCode("ls", "266", "Lesotho"));
        countries.add(new ModelCountyCode("lt", "370", "Lithuania"));
        countries.add(new ModelCountyCode("lu", "352", "Luxembourg"));
        countries.add(new ModelCountyCode("lv", "371", "Latvia"));
        countries.add(new ModelCountyCode("ly", "218", "Libya"));
        countries.add(new ModelCountyCode("ma", "212", "Morocco"));
        countries.add(new ModelCountyCode("mc", "377", "Monaco"));
        countries.add(new ModelCountyCode("md", "373", "Moldova, Republic Of"));
        countries.add(new ModelCountyCode("me", "382", "Montenegro"));
        countries.add(new ModelCountyCode("mf", "590", "Saint Martin"));
        countries.add(new ModelCountyCode("mg", "261", "Madagascar"));
        countries.add(new ModelCountyCode("mh", "692", "Marshall Islands"));
        countries.add(new ModelCountyCode("mk", "389", "Macedonia (FYROM)"));
        countries.add(new ModelCountyCode("ml", "223", "Mali"));
        countries.add(new ModelCountyCode("mm", "95", "Myanmar"));
        countries.add(new ModelCountyCode("mn", "976", "Mongolia"));
        countries.add(new ModelCountyCode("mo", "853", "Macau"));
        countries.add(new ModelCountyCode("mp", "1", "Northern Mariana Islands"));
        countries.add(new ModelCountyCode("mq", "596", "Martinique"));
        countries.add(new ModelCountyCode("mr", "222", "Mauritania"));
        countries.add(new ModelCountyCode("ms", "1", "Montserrat"));
        countries.add(new ModelCountyCode("mt", "356", "Malta"));
        countries.add(new ModelCountyCode("mu", "230", "Mauritius"));
        countries.add(new ModelCountyCode("mv", "960", "Maldives"));
        countries.add(new ModelCountyCode("mw", "265", "Malawi"));
        countries.add(new ModelCountyCode("mx", "52", "Mexico"));
        countries.add(new ModelCountyCode("my", "60", "Malaysia"));
        countries.add(new ModelCountyCode("mz", "258", "Mozambique"));
        countries.add(new ModelCountyCode("na", "264", "Namibia"));
        countries.add(new ModelCountyCode("nc", "687", "New Caledonia"));
        countries.add(new ModelCountyCode("ne", "227", "Niger"));
        countries.add(new ModelCountyCode("nf", "672", "Norfolk Islands"));
        countries.add(new ModelCountyCode("ng", "234", "Nigeria"));
        countries.add(new ModelCountyCode("ni", "505", "Nicaragua"));
        countries.add(new ModelCountyCode("nl", "31", "Netherlands"));
        countries.add(new ModelCountyCode("no", "47", "Norway"));
        countries.add(new ModelCountyCode("np", "977", "Nepal"));
        countries.add(new ModelCountyCode("nr", "674", "Nauru"));
        countries.add(new ModelCountyCode("nu", "683", "Niue"));
        countries.add(new ModelCountyCode("nz", "64", "New Zealand"));
        countries.add(new ModelCountyCode("om", "968", "Oman"));
        countries.add(new ModelCountyCode("pa", "507", "Panama"));
        countries.add(new ModelCountyCode("pe", "51", "Peru"));
        countries.add(new ModelCountyCode("pf", "689", "French Polynesia"));
        countries.add(new ModelCountyCode("pg", "675", "Papua New Guinea"));
        countries.add(new ModelCountyCode("ph", "63", "Philippines"));
        countries.add(new ModelCountyCode("pk", "92", "Pakistan"));
        countries.add(new ModelCountyCode("pl", "48", "Poland"));
        countries.add(new ModelCountyCode("pm", "508", "Saint Pierre And Miquelon"));
        countries.add(new ModelCountyCode("pn", "870", "Pitcairn Islands"));
        countries.add(new ModelCountyCode("pr", "1", "Puerto Rico"));
        countries.add(new ModelCountyCode("ps", "970", "Palestine"));
        countries.add(new ModelCountyCode("pt", "351", "Portugal"));
        countries.add(new ModelCountyCode("pw", "680", "Palau"));
        countries.add(new ModelCountyCode("py", "595", "Paraguay"));
        countries.add(new ModelCountyCode("qa", "974", "Qatar"));
        countries.add(new ModelCountyCode("re", "262", "Réunion"));
        countries.add(new ModelCountyCode("ro", "40", "Romania"));
        countries.add(new ModelCountyCode("rs", "381", "Serbia"));
        countries.add(new ModelCountyCode("ru", "7", "Russian Federation"));
        countries.add(new ModelCountyCode("rw", "250", "Rwanda"));
        countries.add(new ModelCountyCode("sa", "966", "Saudi Arabia"));
        countries.add(new ModelCountyCode("sb", "677", "Solomon Islands"));
        countries.add(new ModelCountyCode("sc", "248", "Seychelles"));
        countries.add(new ModelCountyCode("sd", "249", "Sudan"));
        countries.add(new ModelCountyCode("se", "46", "Sweden"));
        countries.add(new ModelCountyCode("sg", "65", "Singapore"));
        countries.add(new ModelCountyCode("sh", "290", "Saint Helena, Ascension And Tristan Da Cunha"));
        countries.add(new ModelCountyCode("si", "386", "Slovenia"));
        countries.add(new ModelCountyCode("sk", "421", "Slovakia"));
        countries.add(new ModelCountyCode("sl", "232", "Sierra Leone"));
        countries.add(new ModelCountyCode("sm", "378", "San Marino"));
        countries.add(new ModelCountyCode("sn", "221", "Senegal"));
        countries.add(new ModelCountyCode("so", "252", "Somalia"));
        countries.add(new ModelCountyCode("sr", "597", "Suriname"));
        countries.add(new ModelCountyCode("ss", "211", "South Sudan"));
        countries.add(new ModelCountyCode("st", "239", "Sao Tome And Principe"));
        countries.add(new ModelCountyCode("sv", "503", "El Salvador"));
        countries.add(new ModelCountyCode("sx", "1", "Sint Maarten"));
        countries.add(new ModelCountyCode("sy", "963", "Syrian Arab Republic"));
        countries.add(new ModelCountyCode("sz", "268", "Swaziland"));
        countries.add(new ModelCountyCode("tc", "1", "Turks and Caicos Islands"));
        countries.add(new ModelCountyCode("td", "235", "Chad"));
        countries.add(new ModelCountyCode("tg", "228", "Togo"));
        countries.add(new ModelCountyCode("th", "66", "Thailand"));
        countries.add(new ModelCountyCode("tj", "992", "Tajikistan"));
        countries.add(new ModelCountyCode("tk", "690", "Tokelau"));
        countries.add(new ModelCountyCode("tl", "670", "Timor-leste"));
        countries.add(new ModelCountyCode("tm", "993", "Turkmenistan"));
        countries.add(new ModelCountyCode("tn", "216", "Tunisia"));
        countries.add(new ModelCountyCode("to", "676", "Tonga"));
        countries.add(new ModelCountyCode("tr", "90", "Turkey"));
        countries.add(new ModelCountyCode("tt", "1", "Trinidad &amp; Tobago"));
        countries.add(new ModelCountyCode("tv", "688", "Tuvalu"));
        countries.add(new ModelCountyCode("tw", "886", "Taiwan"));
        countries.add(new ModelCountyCode("tz", "255", "Tanzania, United Republic Of"));
        countries.add(new ModelCountyCode("ua", "380", "Ukraine"));
        countries.add(new ModelCountyCode("ug", "256", "Uganda"));
        countries.add(new ModelCountyCode("us", "1", "United States"));
        countries.add(new ModelCountyCode("uy", "598", "Uruguay"));
        countries.add(new ModelCountyCode("uz", "998", "Uzbekistan"));
        countries.add(new ModelCountyCode("va", "379", "Holy See (vatican City State)"));
        countries.add(new ModelCountyCode("vc", "1", "Saint Vincent &amp; The Grenadines"));
        countries.add(new ModelCountyCode("ve", "58", "Venezuela, Bolivarian Republic Of"));
        countries.add(new ModelCountyCode("vg", "1", "British Virgin Islands"));
        countries.add(new ModelCountyCode("vi", "1", "US Virgin Islands"));
        countries.add(new ModelCountyCode("vn", "84", "Vietnam"));
        countries.add(new ModelCountyCode("vu", "678", "Vanuatu"));
        countries.add(new ModelCountyCode("wf", "681", "Wallis And Futuna"));
        countries.add(new ModelCountyCode("ws", "685", "Samoa"));
        countries.add(new ModelCountyCode("xk", "383", "Kosovo"));
        countries.add(new ModelCountyCode("ye", "967", "Yemen"));
        countries.add(new ModelCountyCode("yt", "262", "Mayotte"));
        countries.add(new ModelCountyCode("za", "27", "South Africa"));
        countries.add(new ModelCountyCode("zm", "260", "Zambia"));
        countries.add(new ModelCountyCode("zw", "263", "Zimbabwe"));

        return countries;
    }
}
